Practica12/giw/giw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('preguntas/', include('preguntas.urls')),
]

Practica12/giw/preguntas/urls.py
"""
Definición de las rutas de la app, enlazando las funciones que las manejan
"""
from django.urls import path
from preguntas import views

app_name = "preguntas"

urlpatterns = [
    path('', views.lista_preguntas, name='lista_preguntas'),
    path('<int:pk>/', views.detalle_pregunta, name='detalle_pregunta'),
    path('<int:pk>/respuesta/', views.agregar_pregunta, name='agregar_pregunta'),
    path('login/', views.loginfunct, name='login'),
    path('logout/', views.logoutfunct, name='logout'),
    path('nueva/', views.agregar_pregunta, name='agregar_pregunta'),
]

Practica12/giw/preguntas/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Pregunta(models.Model):

    ident = models.BigAutoField(primary_key=True)

    titulo = models.CharField(max_length=250)
    texto = models.TextField(max_length=5000)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def num_respuestas(self):
        return self.respuesta_set.count()

    def __str__(self):
        return self.titulo

class Respuesta(models.Model):

    ident = models.BigAutoField(primary_key=True)

    texto = models.TextField(max_length=5000)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)

    def __str__(self):
        return self.texto[:50]

Practica12/giw/preguntas/forms.py
from django import forms

class LoginForm(forms.Form):
    """Formulario para autenticar usuarios"""
    username = forms.CharField(label='Nombre de usuario', max_length=100)
    password = forms.CharField(label='Contraseña', max_length=100, widget=forms.PasswordInput)

class PreguntaForm(forms.Form):
    """Formulario para añadir preguntas"""
    titulo = forms.CharField(max_length=250, required=True, label='Título')
    texto = forms.CharField(widget=forms.Textarea, max_length=5000, required=True, label='Pregunta')

class RespuestaForm(forms.Form):
    """Formulario para añadir respuestas"""
    texto = forms.CharField(widget=forms.Textarea, max_length=5000, required=True, label='Respuesta')

Practica12/giw/preguntas/views.py
# Create your views here.

"""
Fichero con las funciones que manejan las peticiones HTTP
"""
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_http_methods
from django.core.exceptions import ValidationError

from preguntas.forms import PreguntaForm, RespuestaForm, LoginForm
from preguntas.models import Pregunta, Respuesta

@require_GET
def lista_preguntas(request):
    """ Muestra la lista de preguntas, ordenadas por fecha (más nuevas primero) """
    preguntas = Pregunta.objects.order_by('-fecha_creacion')
    form = PreguntaForm() if request.user.is_authenticated else None
    return render(request, "lista_preguntas.html", {'preguntas': preguntas, 'form': form})


@login_required(login_url='preguntas:login')
@require_http_methods(["POST"])
def agregar_pregunta(request):
    """ Recibe un formulario y crea una nueva pregunta """
    form = PreguntaForm(request.POST)

    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    titulo_f = form.cleaned_data['titulo']
    texto_f = form.cleaned_data['texto']

    pregunta = Pregunta(titulo=titulo_f, texto=texto_f, autor=request.user)

    try:
        pregunta.full_clean()
        pregunta.save()
    except ValidationError:
        return HttpResponseBadRequest("Pregunta mal formada")

    return redirect(reverse('preguntas:lista_preguntas'))


@login_required(login_url='preguntas:login')
@require_http_methods(["GET", "POST"])
def detalle_pregunta(request, pk):
    """ Muestra el detalle de una pregunta y permite añadir respuestas """
    pregunta = get_object_or_404(Pregunta, pk=pk)
    respuestas = pregunta.respuesta_set.order_by('-fecha_creacion')

    if request.method == "GET":
        form = RespuestaForm()
        return render(request, "detalle_pregunta.html", {'pregunta': pregunta, 'respuestas': respuestas, 'form': form})

    form = RespuestaForm(request.POST)

    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    texto_f = form.cleaned_data['texto']

    respuesta = Respuesta(texto=texto_f, autor=request.user, pregunta=pregunta)

    try:
        respuesta.full_clean()
        respuesta.save()
    except ValidationError:
        return HttpResponseBadRequest("Respuesta mal formada")

    return redirect(reverse('preguntas:detalle_pregunta', kwargs={'pk': pk}))


@require_http_methods(["GET", "POST"])
def loginfunct(request):
    """ Muestra el formulario (GET) o realiza la autenticación (POST) """
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {'login_form': form})

    form = LoginForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest(f"Error en los datos del formulario: {form.errors}")

    username = form.cleaned_data['username']
    password = form.cleaned_data['password']

    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect(reverse('preguntas:lista_preguntas'))

    return render(request, "login.html", {
        'login_form': form,
        'error_message': "Usuario o contraseña incorrectos"
    })

    
@require_GET
def logoutfunct(request):

    logout(request)
    return redirect(reverse('preguntas:lista_preguntas'))

Practica12/giw/preguntas/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}La web para preguntas y respuestas{% endblock %}</title>
</head>

<body>
    <h1>La web para preguntas y respuestas</h1>
    <p>
        {% if request.user.is_authenticated %}
        <span>Bienvenido {{ request.user.username }}</span>
        <a href="{% url 'preguntas:logout' %}"><button type="button">Cerrar sesión</button></a>
        <a href="{% url 'preguntas:lista_preguntas' %}"><button type="button">Ver preguntas</button></a>
        {% else %}
        <span>No autenticado</span>
        <a href="{% url 'preguntas:login' %}"><button type="button">Iniciar sesión</button></a>
        {% endif %}
    </p>
    
    {% block content %}
    CONTENIDO
    {% endblock %}
</body>

</html>

Practica12/giw/preguntas/templates/detalle_pregunta.html
{% extends "base.html" %}

{% block title %}
Detalle de pregunta
{% endblock %}

{% block content %}
<h2>{{ pregunta.titulo }} -- {{pregunta.autor.username }} ({{ pregunta.fecha_creacion }})</h2>

<p>{{ pregunta.texto }}</p>

{% if respuestas %}
<h2>Respuestas</h2>
<ol>
    {% for respuesta in respuestas %}
    <li>
        {{ respuesta.texto }} <br>
        {{ respuesta.autor.username }} ({{ respuesta.fecha_creacion }})
    </li>
    {% endfor %}
</ol>
{% endif %}

{% if user.is_authenticated %}
<h3>Añadir nueva respuesta</h3>
<form method="post" action="{% url 'preguntas:detalle_pregunta' pregunta.ident %}">
    <table>
        {{ form }}
    </table>
    {% csrf_token %}
    <button type="submit">Enviar respuesta</button>
</form>
{% endif %}
{% endblock %}

Practica12/giw/preguntas/templates/lista_preguntas.html
{% extends "base.html" %}

{% block title %}
Preguntas
{% endblock %}

{% block content %}
<h2>Preguntas</h2>
<ul>
{% for pregunta in preguntas %}
    <li>
        <a href="{% url 'preguntas:detalle_pregunta' pregunta.ident %}">
            <strong>{{ pregunta.titulo }}</strong>
        </a>
        -- {{ pregunta.autor.username }} ({{ pregunta.fecha_creacion }})<br>
        {{ pregunta.num_respuestas }} respuestas
    </li>
{% endfor %}
</ul>

{% if user.is_authenticated %}
<h3>Añadir nueva pregunta</h3>
<form method="post" action="{% url 'preguntas:agregar_pregunta' %}">
    <table>
        {{ form }}
    </table>
    {% csrf_token %}
    <button type="submit">Enviar pregunta</button>
</form>
{% endif %}
{% endblock %}

Practica12/giw/preguntas/templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Iniciar sesión</title>
</head>
<body>
<h1>La web para preguntas y respuestas</h1>
<p>
    {% if request.user.is_authenticated %}
        Bienvenido {{ request.user.username }}
    {% else %}
        No autenticado <a href="{% url 'preguntas:login' %}"><button type="button">Iniciar sesión</button></a>
    {% endif %}
</p>

{% if error_message %}
<h2>{{ error_message }}</h2>
{% else %}
<form method="post">
    {% csrf_token %}
    <p><strong>{{ login_form.username.label }}</strong>: {{ login_form.username }}</p>
    <p><strong>{{ login_form.password.label }}</strong>: {{ login_form.password }}</p>
    <button type="submit">Iniciar sesión</button>
</form>
{% endif %}
</body>
</html>